### ISSUE TITLE
Add email and split name in payment topic

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/Payments#11]
As I now want to create contacts for every payment, I would like to have the email-adress to identify the same customer.
I also would prefer the fullname to be split into firstname and lastname if possible.

**Comment by Ekwav** [comment]
What should be done if the splitting of first and last name is not apparent?
Stripe only has a `name` field

**Comment by matthias-luger** [comment]
Only the lastname is a required field for contacts, so I guess, just put it in there then

**Comment by Ekwav** [comment]
Keeping the `fullName` and adding the `firstName` and `lastName` properties so you can decide when to take what. 
Also adding the email-address used for checkout, note that its not necessarily sufficient to differentiate customers, the `UserId` should be used for that
