### ISSUE TITLE
starter premium does not extend if higher product is already active

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/Payments#5]
![Image](https://user-images.githubusercontent.com/58751503/191358895-69f2d388-8c71-456e-87ee-0a3703bdcfe6.png)

**Comment by Ekwav** [comment]
@matthias-luger can't reproduce that, how/where did you buy?

**Comment by matthias-luger** [comment]
Cant reproduce it either anymore....
Seems to be fixed
